### ISSUE TITLE
Quince never loads Alazar 

### ISSUE THREAD

**Issue by calebjordan** [BBN-Q/Quince#14]
Quince can never find the Alazar source on startup. Have to add manually each time. Once added it does save properly.

**Comment by grahamrow** [comment]
Thanks for trying out quince! Just to clarify, you mean that loading a config file with Alazar related streams fails to load those nodes? I think I'm hung up on whether you mean "source" as in the Alazar node or "source" as in source code (i.e. the Alazar library). 

Some preliminary questions:
1. How are you loading quince? From a notebook via the `quince()` convenience function within Auspex or from command line?
2. Is quince running in the same python environment as auspex?
3. Do you see menu items for adding alazar stream selectors in the Quince context menu (right click on the canvas)?
4. Could you post your config file(s) or at least the relevant portions?

The way quince finds filters is by scraping Auspex' package structure and inspecting all modules that subclass `Filter`. The first thing we need to sort out is whether the problem is in scraping these source files or in reading your config file.

**Comment by calebjordan** [comment]
Sorry for not being more detailed, I was hoping this was a known issue. 

1. From command line, using the BBN_MEAS_FILE env variable. 

2. Yes, only one conda env on the machine

3. By 'manually add', I meant through the GUI. I can add it, drag the connection, and save it properly. But if I close quince and reopen, the Alazar is gone again.

4. 

filters: 

```
Stream-q1:
  type: AlazarStreamSelector
  source: AlazarATS9870-1
  channel: 1

  enabled: true
```

instruments:

 ```
 AlazarATS9870-1:
    type: AlazarATS9870
    enabled: true
    label: Alazar
    address: 1
    acquire_mode: digitizer
    bandwidth: Full
    clock_type: ref
    delay: 1e-7
    record_length: 4096
    nbr_samples: 4096
    nbr_segments: 1
    nbr_waveforms: 1
    nbr_round_robins: 2500
    sampling_rate: 1e9
    trigger_coupling: DC
    trigger_level: 100
    trigger_slope: rising
    trigger_source: Ext
    vertical_coupling: AC
    vertical_offset: 0
    vertical_scale: 2
```

When I load quince I get a 
`Could not find source for  Stream-q1 : AlazarATS9870-1 source`
prompt.

**Comment by grahamrow** [comment]
Okay, problem located. Quince looks to see if `rx_channels` exists in the settings in order to decide whether the instrument is a digitizer — this should be made more explicit, as the Alazar is currently missing a YAML template.

This config works for me:
```YAML
filters:
  Stream-q1:
    type: AlazarStreamSelector
    source: AlazarATS9870-1
    channel: 2
    enabled: true

instruments:
  AlazarATS9870-1:
    type: AlazarATS9870
    enabled: true
    label: Alazar
    rx_channels:
      '1':
      '2':
    address: 1
    acquire_mode: digitizer
    bandwidth: Full
    clock_type: ref
    delay: 1.0e-07
    record_length: 4096
    nbr_samples: 4096
    nbr_segments: 1
    nbr_waveforms: 1
    nbr_round_robins: 2500
    sampling_rate: 1000000000.0
    trigger_coupling: DC
    trigger_level: 100
    trigger_slope: rising
    trigger_source: Ext
    vertical_coupling: AC
    vertical_offset: 0
    vertical_scale: 2

config:
  AWGDir: /Users/me/workspace/AWG/
  KernelDir: /Users/me/workspace/kernels/
  LogDir: /Users/me/workspace/auspex_log/

```
